name: Setup
description: Initial setup for workflows

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install Prettier
      shell: bash
      run: npm install -g prettier
