name: Format

on:
  push:
    
permissions:
  pull-requests: write
  

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:   
          node-version: 18

      - name: Install Prettier
        shell: bash
        run: npm install -g prettier

      - name: Check Formatting
        id: check
        continue-on-error: true
        run: prettier --check .

      - name: Fix Formatting
        if: steps.check.outcome == 'failure'
        run: prettier --write .

      - name: Commit Changes
        if: steps.check.outcome == 'failure'
        uses: EndBug/add-and-commit@v9
        with:
          message: Format documents
          new_branch: ${{ github.event.pull_request.head.ref }}

      - name: Comment on PR
        if: steps.check.outcome == 'failure'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            This pull request contained files that were not formatted correctly and have been formatted automatically. Authors: you do not need to do anything but pull the changes.

      