name: Generate issues index

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Generate issues index
        run: deno run --allow-write=./issues/issues.json --allow-net --allow-env=GITHUB_TOKEN .github/actions/generate_issues_index.ts

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Regenerate issues index
          committer_name: GitHub Actions
          committer_email: actions@github.com
